[package]
name = "enc-kv-store"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
argon2 = { version = "0.5.3", features = ["std"] }
once_cell = "1.21.3"
rand = "0.9.2"
ring = "0.17.14"
serde = { version = "1.0.228", features = ["derive"] }
